[package]
name = "flap"
version = "1.1.5"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
colored = "2.0"
anyhow = "1.0"
self_update = { version = "0.41", features = ["archive-zip", "archive-tar"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.52"

[[bin]]
name = "flap"
path = "src/main.rs"

[[bin]]
name = "flap_installer"
path = "src/bin/flap_installer.rs"
